"""question log update

Revision ID: 1d45d147e776
Revises: 35808f6e57f8
Create Date: 2026-06-15 02:23:31.473804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d45d147e776'
down_revision: Union[str, Sequence[str], None] = '35808f6e57f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_logs', sa.Column('top_score', sa.Float(), nullable=True))
    op.add_column('question_logs', sa.Column('chunk_count', sa.Integer(), nullable=True))
    op.add_column('question_logs', sa.Column('context_length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_logs', 'context_length')
    op.drop_column('question_logs', 'chunk_count')
    op.drop_column('question_logs', 'top_score')
    # ### end Alembic commands ###
