"""add ragas metrics

Revision ID: 6fb5680b7de4
Revises: fe2ac9ca9a1c
Create Date: 2026-06-15 23:12:51.065244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb5680b7de4'
down_revision: Union[str, Sequence[str], None] = 'fe2ac9ca9a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_results', sa.Column('answer_relevancy', sa.Float(), nullable=True))
    op.add_column('evaluation_results', sa.Column('faithfulness', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation_results', 'faithfulness')
    op.drop_column('evaluation_results', 'answer_relevancy')
    # ### end Alembic commands ###
