"""created_at evalmod

Revision ID: 6f20d8666e2e
Revises: e3f13786ce7f
Create Date: 2026-06-15 13:55:07.299466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f20d8666e2e'
down_revision: Union[str, Sequence[str], None] = 'e3f13786ce7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_datasets', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluation_datasets', 'created_at')
    # ### end Alembic commands ###
